// This file is auto-generated by Lovable. Do not modify it.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import { supabase } from "../supabase/client";
const lovableAuth = createLovableAuth({});

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: "google" | "apple", opts?: SignInOptions) => {
      const result = await lovableAuth.signInWithOAuth(provider, {
        redirect_uri: opts?.redirect_uri,
        extraParams: {
          ...opts?.extraParams,
        },
      });

      if (result.redirected) {
        return result;
      }

      if (result.error) {
        return result;
      }

      try {
        // Set the session with the received tokens
        const { error: sessionError } = await supabase.auth.setSession(result.tokens);
        if (sessionError) {
          console.error("Failed to set session:", sessionError);
          return { error: sessionError };
        }
        
        // Wait for session to propagate through Supabase client
        await new Promise(resolve => setTimeout(resolve, 1000));
        
        // Verify the session was set correctly before attempting refresh
        const { data: sessionData } = await supabase.auth.getSession();
        if (sessionData?.session) {
          // Only refresh if we have a valid session
          try {
            await supabase.auth.refreshSession();
          } catch (refreshError) {
            // Refresh failed but session might still be valid, continue
            console.warn("Session refresh warning:", refreshError);
          }
        }
      } catch (e) {
        console.error("OAuth session error:", e);
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }
      return result;
    },
  },
};
